token: ''
prefix: +
channels:
  log:
    commands:
      - channel-id-1
    game_events:
      - channel-id-2
    bans:
      - channel-id-3
    reports:
      - channel-id-4
    staff_copy:
      - channel-id-5
  topic:
    - channel-id-5
  command:
    - channel-id-6
commands:
  role_id_1:
    - di
    - discordintegration
discord_server:
  id: ''
tcp_server:
  port: 9000
  ip_address: 127.0.0.1
keep_alive_interval: 2000
messages_delay: 1000
is_debug_enabled: false
